spring:
  datasource:
    url: jdbc:mysql://localhost:3307/osahaneat
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto:
server:
  port: 8083

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB
jwt:
  privateKey: uAeWB1adohWArb5E2NNxFYKL3Q39dOPotweKK0/pR+8=

upload:
  path: \Users\user\Desktop\desktop